### ISSUE TITLE
Time to roll a new version and publish

### ISSUE THREAD

**Issue by dancrumb** [Jellyvision/lateralus#14]

**Comment by jeremyckahn** [comment]
Agreed.  I'm a bit bogged down at the moment, so I will try to get to this in the next few days!

**Comment by jeremyckahn** [comment]
I can't get the Lateralus Mocha tests to run in my CLI anymore, and I'd prefer not to publish a new version until I can.  I spent a little time poking at the code to get it to run — the project devDependencies are so out of date that at this point, it's worth it to invest the time to bring Lateralus into the present à la https://github.com/jeremyckahn/modern-js-project.  So, dropping Grunt and RequireJS for Webpack and NPM scripts.  This _shouldn't_ affect downstream code, and it would make this project much easier to work with.

I'll get started on a PR for this as I have time, unless you'd like me to prioritize an NPM version to unblock you.

**Comment by dancrumb** [comment]
I think that's a worthy goal. However #f1315679 is a blocker for webpack work.

I think a patch bump would suffice for this since the current value for main has no reasonable usage.

**Comment by dancrumb** [comment]
So, I guess I'm voting for a publish asap
